default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: 'myuser'
  password: 'mypass'

development:
  <<: *default
  database: vanzeiro_development

test:
  <<: *default
  database: vanzeiro_test