default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: olh234
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: mvp_development

test:
  <<: *default
  database: mvp_test

production:
  <<: *default
  database: mvp_production
