development:
  facebook_key: "388088214678210"
  facebook_secret: "a152dedb6a824fbecbae4c08b80ad254"

  google_key: "229935539709-f0tcotjufjrp659k1hsn1hci00iralsp.apps.googleusercontent.com"
  google_secret: "u_DWriXOXkIE1hDPzDEpQqeP"

production:
  facebook_key: "380297832123915"
  facebook_secret: "51c5405c4afa8f6729e7372f6be45b97"

  google_key: "850732988837-0qmnj130ec1qdla15g1ggspb0hf3lmne.apps.googleusercontent.com"
  google_secret: "XVOPH0afs_MyvxQO2EX2riy1"